version: "3"

services:
  apisix:
    image: apache/apisix:whole
    restart: unless-stopped
    volumes:
      - ./all-in-one/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro

    ports:
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "2379:2379/tcp"
    # networks:
    #  - apisix

  apisix-dashboard:
    image: apache/apisix-dashboard:whole
    restart: unless-stopped
    volumes:
      - ./all-in-one/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./all-in-one/apisix-dashboard/config.yaml:/usr/local/apisix-dashboard/conf/config.yaml:ro
    ports:
      - "19080:9080"
      - "19091:9091" 
      - "12379:2379" 
      - "19000:9000"
    # networks:
    #  - apisix


# networks:
#   apisix:
#     driver: bridge